# Generated by Django 3.2.10 on 2024-01-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240112_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher'),
            preserve_default=False,
        ),
    ]
