# Generated by Django 3.2.10 on 2024-01-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_file_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='file',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='record',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
        migrations.CreateModel(
            name='DisciplineTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.record')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='disciplines', through='myapp.DisciplineTeacher', to='myapp.Teacher'),
        ),
    ]
