# Generated by Django 3.2.10 on 2024-01-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240114_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplineteacher',
            name='record',
        ),
        migrations.RemoveField(
            model_name='record',
            name='file',
        ),
        migrations.RemoveField(
            model_name='record',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='surname',
        ),
        migrations.AddField(
            model_name='disciplineteacher',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.discipline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='files',
            field=models.ManyToManyField(to='myapp.File'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='disciplines',
            field=models.ManyToManyField(blank=True, through='myapp.DisciplineTeacher', to='myapp.Discipline'),
        ),
        migrations.AlterField(
            model_name='record',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='myapp.discipline'),
        ),
    ]
