# Generated by Django 3.2.10 on 2024-02-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20240203_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uploaded_by',
        ),
    ]
