# Generated by Django 3.2.10 on 2024-02-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20240203_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='group',
        ),
        migrations.AddField(
            model_name='record',
            name='group',
            field=models.ManyToManyField(to='myapp.Group'),
        ),
    ]
